"""Chapter hierarchy and non-Canon navigation-memory contracts."""

from novel_core.navigation.models import (
    Chapter,
    ChapterSummary,
    EntityMention,
    EntityMentionForm,
    EntityPresenceKind,
    EntityProminence,
    EntityResolutionStatus,
    SceneEntityOccurrence,
    SceneSummary,
    SceneSummaryDependency,
    SceneTrace,
    chapter_summary_is_stale,
    scene_summary_digest,
    scene_summary_is_stale,
    scene_trace_digest,
    scene_trace_is_stale,
    validate_chapter_bindings,
)

__all__ = [
    "Chapter",
    "ChapterSummary",
    "EntityMention",
    "EntityMentionForm",
    "EntityPresenceKind",
    "EntityProminence",
    "EntityResolutionStatus",
    "SceneEntityOccurrence",
    "SceneSummary",
    "SceneSummaryDependency",
    "SceneTrace",
    "chapter_summary_is_stale",
    "scene_summary_digest",
    "scene_summary_is_stale",
    "scene_trace_digest",
    "scene_trace_is_stale",
    "validate_chapter_bindings",
]
