"""Storage-independent use cases for local novel projects."""

from novel_application.catalog import ProjectCatalogService
from novel_application.creation import (
    BootstrapService,
    DraftService,
    IntentService,
    PublicationService,
    ReviewService,
    SessionNavigationService,
    WritingSessionService,
)
from novel_application.errors import (
    ApprovalMismatchError,
    ChapterNotFoundError,
    FullTextSearchUnavailableError,
    LedgerConflictError,
    LedgerReadError,
    ManuscriptReadError,
    NavigationMemoryReadError,
    ProjectAlreadyExistsError,
    ProjectBusyError,
    ProjectCatalogBusyError,
    ProjectCatalogEntryNotFoundError,
    ProjectCatalogPathConflictError,
    ProjectCatalogReadError,
    ProjectCatalogWriteError,
    ProjectIdentityConflictError,
    ProjectionOutOfDateError,
    ProjectManifestInvalidError,
    ProjectNotBootstrappedError,
    ProjectNotFoundError,
    ProjectPathInvalidError,
    ProjectSelectionMismatchError,
    PublicationRecoveryRequiredError,
    RevisionConflictError,
    SceneHistoryAccessError,
    SceneNotFoundError,
    WorkflowNotFoundError,
    WorkflowStateError,
)
from novel_application.memory import NavigationMemoryService, NavigationMemoryWriter
from novel_application.models import (
    AssertionHistoryItem,
    ChapterSceneItem,
    ChapterSummaryItem,
    EventOrder,
    ExactSceneText,
    ProjectCreationResult,
    ProjectDetails,
    ProjectHealth,
    ProjectionStatus,
    ProjectListItem,
    ProjectRegistrationResult,
    ProjectResolution,
    SummaryRetrievalMethod,
    SummarySearchHit,
)
from novel_application.queries import CanonQueryService
from novel_application.services import ProjectService

__all__ = [
    "ApprovalMismatchError",
    "AssertionHistoryItem",
    "BootstrapService",
    "ChapterNotFoundError",
    "ChapterSceneItem",
    "ChapterSummaryItem",
    "CanonQueryService",
    "DraftService",
    "EventOrder",
    "ExactSceneText",
    "FullTextSearchUnavailableError",
    "IntentService",
    "LedgerConflictError",
    "LedgerReadError",
    "ManuscriptReadError",
    "NavigationMemoryReadError",
    "NavigationMemoryService",
    "NavigationMemoryWriter",
    "ProjectAlreadyExistsError",
    "ProjectBusyError",
    "ProjectCatalogBusyError",
    "ProjectCatalogEntryNotFoundError",
    "ProjectCatalogPathConflictError",
    "ProjectCatalogReadError",
    "ProjectCatalogService",
    "ProjectCatalogWriteError",
    "ProjectCreationResult",
    "ProjectDetails",
    "ProjectHealth",
    "ProjectIdentityConflictError",
    "ProjectListItem",
    "ProjectManifestInvalidError",
    "ProjectNotBootstrappedError",
    "ProjectNotFoundError",
    "ProjectPathInvalidError",
    "ProjectRegistrationResult",
    "ProjectResolution",
    "ProjectSelectionMismatchError",
    "ProjectService",
    "ProjectionOutOfDateError",
    "ProjectionStatus",
    "PublicationRecoveryRequiredError",
    "PublicationService",
    "RevisionConflictError",
    "ReviewService",
    "SceneHistoryAccessError",
    "SceneNotFoundError",
    "SessionNavigationService",
    "SummaryRetrievalMethod",
    "SummarySearchHit",
    "WorkflowNotFoundError",
    "WorkflowStateError",
    "WritingSessionService",
]
